# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 18:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basename', models.CharField(db_index=True, max_length=1000, unique=True)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('DATE_OBS', models.DateTimeField(db_index=True, help_text='Time of observation in UTC. FITS header: DATE-OBS', null=True, verbose_name='DATE-OBS')),
                ('PROPID', models.CharField(default='', help_text='Textual proposal id. FITS header: PROPID', max_length=200)),
                ('INSTRUME', models.CharField(default='', help_text='Instrument used. FITS header: INSTRUME', max_length=10)),
                ('OBJECT', models.CharField(db_index=True, default='', help_text='Target object name. FITS header: OBJECT', max_length=200)),
                ('RLEVEL', models.SmallIntegerField(default=0, help_text='Reduction level of the frame')),
                ('SITEID', models.CharField(default='', help_text='Originating site. FITS header: SITEID', max_length=3)),
                ('TELID', models.CharField(default='', help_text='Originating telescope. FITS header: TELID', max_length=4)),
                ('EXPTIME', models.DecimalField(decimal_places=3, help_text='Exposure time, in seconds. FITS header: EXPTIME', max_digits=10, null=True)),
                ('FILTER', models.CharField(default='', help_text='Filter used. FITS header: FILTER', max_length=100)),
                ('L1PUBDAT', models.DateTimeField(db_index=True, help_text='The date the frame becomes public. FITS header: L1PUBDAT', null=True)),
                ('OBSTYPE', models.CharField(choices=[('BIAS', 'BIAS'), ('DARK', 'DARK'), ('EXPERIMENTAL', 'EXPERIMENTAL'), ('EXPOSE', 'EXPOSE'), ('SKYFLAT', 'SKYFLAT'), ('STANDARD', 'STANDARD'), ('TRAILED', 'TRAILED'), ('GUIDE', 'GUIDE'), ('SPECTRUM', 'SPECTRUM'), ('ARC', 'ARC'), ('LAMPFLAT', 'LAMPFLAT')], default='', help_text='Type of observation. FITS header: OBSTYPE', max_length=20)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('related_frames', models.ManyToManyField(blank=True, related_name='_frame_related_frames_+', to='frames.Frame')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Headers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('frame', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frames.Frame')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('md5', models.CharField(max_length=32, unique=True)),
                ('extension', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frames.Frame')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
