# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 18:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 12, 16, 18, 56, 38, 922366, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
