# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0002_auto_20160229_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='BLKUID',
            field=models.PositiveIntegerField(db_index=True, help_text='Block id from the pond. FITS header: BLKUID', null=True),
        ),
    ]
