# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0002_auto_20160119_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='USERID',
        ),
    ]
