# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0002_auto_20160125_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='EXPTIME',
            field=models.DecimalField(decimal_places=3, help_text='Exposure time, in seconds. FITS header: EXPTIME', max_digits=10, null=True),
        ),
    ]
