# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 22:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0002_frame_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headers',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
