# Generated by Django 2.0.13 on 2019-04-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0007_auto_20170831_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='EXPTIME',
            field=models.DecimalField(decimal_places=6, help_text='Exposure time, in seconds. FITS header: EXPTIME', max_digits=13, null=True),
        ),
    ]
