# Generated by Django 2.0.13 on 2019-08-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0008_auto_20190417_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='INSTRUME',
            field=models.CharField(default='', help_text='Instrument used. FITS header: INSTRUME', max_length=64),
        ),
    ]
