# Generated by Django 2.0.13 on 2019-12-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0009_auto_20190807_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='migrated',
            field=models.BooleanField(default=False),
        ),
    ]
