# Generated by Django 2.0.13 on 2020-02-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0011_frame_day_obs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='migrated',
        ),
    ]
