# Generated by Django 2.0.13 on 2020-11-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0011_frame_day_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='FILTER',
            field=models.CharField(blank=True, default='', help_text='Filter used. FITS header: FILTER', max_length=100),
        ),
        migrations.AlterField(
            model_name='frame',
            name='OBSTYPE',
            field=models.CharField(choices=[('BIAS', 'BIAS'), ('DARK', 'DARK'), ('EXPERIMENTAL', 'EXPERIMENTAL'), ('EXPOSE', 'EXPOSE'), ('SKYFLAT', 'SKYFLAT'), ('STANDARD', 'STANDARD'), ('TRAILED', 'TRAILED'), ('GUIDE', 'GUIDE'), ('SPECTRUM', 'SPECTRUM'), ('ARC', 'ARC'), ('LAMPFLAT', 'LAMPFLAT'), ('DOMEFLAT', 'DOMEFLAT'), ('CATALOG', 'CATALOG'), ('BPM', 'BPM'), ('TARGET', 'TARGET'), ('TEMPLATE', 'TEMPLATE'), ('OBJECT', 'OBJECT'), ('TRACE', 'TRACE'), ('DOUBLE', 'DOUBLE')], default='', help_text='Type of observation. FITS header: OBSTYPE', max_length=20),
        ),
    ]
