# Generated by Django 2.0.13 on 2020-12-17 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0012_auto_20201112_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='migrated',
        ),
    ]
