# Generated by Django 2.2.26 on 2022-01-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0013_remove_migrated_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='configuration_type',
            field=models.CharField(help_text='Configuration type of the observation', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='exposure_time',
            field=models.FloatField(help_text='Exposure time, in seconds', null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='instrument_id',
            field=models.CharField(help_text='Instrument used', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='observation_date',
            field=models.DateTimeField(db_index=True, help_text='Time of observation in UTC', null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='observation_day',
            field=models.DateField(help_text='Observing Night in YYYYMMDD', null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='observation_id',
            field=models.PositiveIntegerField(db_index=True, help_text='Unique id associated with the observation', null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='primary_optical_element',
            field=models.CharField(blank=True, help_text='Primary Optical Element used. FITS header: FILTER', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='proposal_id',
            field=models.CharField(blank=True, help_text='Textual proposal id', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='public_date',
            field=models.DateTimeField(db_index=True, help_text='The date the frame becomes public', null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='reduction_level',
            field=models.SmallIntegerField(help_text='Reduction level of the frame', null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='request_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Unique id associated with the request this observation is a part of', null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='site_id',
            field=models.CharField(help_text='Originating site code. Usually the 3 character airport code of the nearest airport', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='target_name',
            field=models.CharField(blank=True, db_index=True, help_text='Target object name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='telescope_id',
            field=models.CharField(help_text='Originating telescope 4 character code. Ex. 1m0a or 0m4b', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='BLKUID',
            field=models.PositiveIntegerField(db_index=True, help_text='Unique id associated with the observation', null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='DATE_OBS',
            field=models.DateTimeField(db_index=True, help_text='Time of observation in UTC', null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='DAY_OBS',
            field=models.DateField(help_text='Observing Night in YYYYMMDD', null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='FILTER',
            field=models.CharField(blank=True, default='', help_text='Primary Optical Element used. FITS header: FILTER', max_length=100),
        ),
        migrations.AlterField(
            model_name='frame',
            name='INSTRUME',
            field=models.CharField(default='', help_text='Instrument used', max_length=64),
        ),
        migrations.AlterField(
            model_name='frame',
            name='L1PUBDAT',
            field=models.DateTimeField(db_index=True, help_text='The date the frame becomes public', null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='OBJECT',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Target object name', max_length=200),
        ),
        migrations.AlterField(
            model_name='frame',
            name='OBSTYPE',
            field=models.CharField(choices=[('BIAS', 'BIAS'), ('DARK', 'DARK'), ('EXPERIMENTAL', 'EXPERIMENTAL'), ('EXPOSE', 'EXPOSE'), ('SKYFLAT', 'SKYFLAT'), ('STANDARD', 'STANDARD'), ('TRAILED', 'TRAILED'), ('GUIDE', 'GUIDE'), ('SPECTRUM', 'SPECTRUM'), ('ARC', 'ARC'), ('LAMPFLAT', 'LAMPFLAT'), ('DOMEFLAT', 'DOMEFLAT'), ('CATALOG', 'CATALOG'), ('BPM', 'BPM'), ('TARGET', 'TARGET'), ('TEMPLATE', 'TEMPLATE'), ('OBJECT', 'OBJECT'), ('TRACE', 'TRACE'), ('DOUBLE', 'DOUBLE')], default='', help_text='Configuration type of the observation', max_length=20),
        ),
        migrations.AlterField(
            model_name='frame',
            name='PROPID',
            field=models.CharField(blank=True, default='', help_text='Textual proposal id', max_length=200),
        ),
        migrations.AlterField(
            model_name='frame',
            name='REQNUM',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Unique id associated with the request this observation is a part of', null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='SITEID',
            field=models.CharField(default='', help_text='Originating site code. Usually the 3 character airport code of the nearest airport', max_length=3),
        ),
        migrations.AlterField(
            model_name='frame',
            name='TELID',
            field=models.CharField(default='', help_text='Originating telescope 4 character code. Ex. 1m0a or 0m4b', max_length=4),
        ),
    ]
