# Generated by Django 2.2.26 on 2022-01-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0014_auto_20220118_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='configuration_type',
            field=models.CharField(default='', help_text='Configuration type of the observation', max_length=20),
        ),
        migrations.AlterField(
            model_name='frame',
            name='instrument_id',
            field=models.CharField(default='', help_text='Instrument used', max_length=64),
        ),
        migrations.AlterField(
            model_name='frame',
            name='primary_optical_element',
            field=models.CharField(blank=True, default='', help_text='Primary Optical Element used. FITS header: FILTER', max_length=100),
        ),
        migrations.AlterField(
            model_name='frame',
            name='proposal_id',
            field=models.CharField(blank=True, default='', help_text='Textual proposal id', max_length=200),
        ),
        migrations.AlterField(
            model_name='frame',
            name='reduction_level',
            field=models.SmallIntegerField(default=0, help_text='Reduction level of the frame'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='site_id',
            field=models.CharField(default='', help_text='Originating site code. Usually the 3 character airport code of the nearest airport', max_length=3),
        ),
        migrations.AlterField(
            model_name='frame',
            name='target_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Target object name', max_length=200),
        ),
        migrations.AlterField(
            model_name='frame',
            name='telescope_id',
            field=models.CharField(default='', help_text='Originating telescope 4 character code. Ex. 1m0a or 0m4b', max_length=4),
        ),
    ]
