# Generated by Django 3.2.12 on 2022-03-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0016_auto_20220218_0815'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='frame',
            index_together={('observation_date', 'public_date', 'site_id', 'telescope_id', 'instrument_id', 'configuration_type', 'primary_optical_element', 'proposal_id')},
        ),
    ]
