# Generated by Django 3.2.15 on 2022-09-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0018_aggregate_index'),
    ]

    operations = [
        migrations.RunSQL(
          # https://www.citusdata.com/blog/2016/10/12/count-performance/#dup_counts_estimated_filtered
          sql="""
          CREATE FUNCTION count_estimate(query text) RETURNS integer AS $$
          DECLARE
            rec   record;
            rows  integer;
          BEGIN
            FOR rec IN EXECUTE 'EXPLAIN ' || query LOOP
              rows := substring(rec."QUERY PLAN" FROM ' rows=([[:digit:]]+)');
              EXIT WHEN rows IS NOT NULL;
            END LOOP;
            RETURN rows;
          END;
          $$ LANGUAGE plpgsql VOLATILE STRICT;
          """,
          reverse_sql="""
          DROP FUNCTION IF EXISTS count_estimate(query text);
          """
        )
    ]
