# Generated by Django 4.2.9 on 2024-04-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0019_count_estimate_func'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='frame',
            name='frames_frame_aggregate',
        ),
        migrations.AlterField(
            model_name='frame',
            name='instrument_id',
            field=models.CharField(blank=True, default='', help_text='Instrument used', max_length=64),
        ),
        migrations.AlterField(
            model_name='frame',
            name='related_frames',
            field=models.ManyToManyField(blank=True, to='frames.frame'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='site_id',
            field=models.CharField(blank=True, default='', help_text='Originating site code. Usually the 3 character airport code of the nearest airport', max_length=3),
        ),
        migrations.AlterField(
            model_name='frame',
            name='telescope_id',
            field=models.CharField(blank=True, default='', help_text='Originating telescope 4 character code. Ex. 1m0a or 0m4b', max_length=4),
        ),
        migrations.AlterField(
            model_name='headers',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
