# Generated by Django 4.2.9 on 2024-05-06 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0020_alter_instrument_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='String description of the size of the thumbnail', max_length=20)),
                ('filename', models.CharField(db_index=True, help_text='The basename of the thumbnail', max_length=1000, unique=True)),
                ('key', models.CharField(default='', help_text='The key used to store the thumbnail in the file store', max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='frame',
            field=models.ForeignKey(blank=True, help_text='The frame this thumbnail is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='frames.frame'),
        ),
    ]
