# Generated by Django 6.0.5 on 2026-05-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0021_add_thumbnail_model'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='frame',
                    name='frames_frame_aggregate',
                ),
                migrations.RenameIndex(
                    model_name='frame',
                    new_name='frames_frame_aggregate',
                    old_fields=('observation_date', 'public_date', 'site_id', 'telescope_id', 'instrument_id', 'configuration_type', 'primary_optical_element', 'proposal_id'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='frame',
            name='related_frames',
            field=models.ManyToManyField(blank=True, to='frames.frame'),
        ),
        migrations.AlterField(
            model_name='headers',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
