# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20160116_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='proposals',
        ),
    ]
